Implemented variants support
contentstack/contentstack-typescript pull request #45
Opened 2024-09-03 06:44 UTC by sunil-lakshman

2024-09-03 07:04 UTC, nadeem-cs requested changes

2024-09-03 07:04 UTC, nadeem-cs commented on package.json
> +  "version": "5.1.0",
@sunil-lakshman This will be 4.2.0. We are going to revert the PR of 5.0.0 most probably.

2024-09-03 07:08 UTC, nadeem-cs approved these changes

2024-09-03 07:21 UTC, harshithad0703 approved these changes
Approved

2024-09-04 06:44 UTC, nadeem-cs approved these changes

2024-09-04 06:48 UTC, merged